name: "first workflow"

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: npm

  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test lint
        run: npm run lint

      - name: Test cases
        run: npm run test

  build_job:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Make React build
        run: npm run build

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/
          retention-days: 7

      - name: "Install Vercel VLI"
        run: npm install -g vercel

      - name: "Deploy to Vercel"
        run: vercel deploy dist --prod --yes --token ${{ secrets.VERCEL_TOKEN }}

  # deploy_job:
  #   needs: [first_job, second_job, build_job]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7

  #     - name: "Install Vercel VLI"
  #       run: npm install -g vercel

  #     - name: "Deploy to Vercel"
  #       run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
